jdbc.dependency.version=@project.version@
quarkus.version=@quarkus.version@
camel.version=@camel.version@
quarkus.artemis.jms.version=@quarkus.artemis.jms.version@
plain.jms.dependencies=mvn:org.apache.camel.forage:forage-jms:@project.version@
quarkus.jms.dependencies=mvn:org.apache.camel.forage:forage-quarkus-jms:@project.version@,mvn:org.apache.camel.forage:forage-quarkus-jms-deployment:@project.version@,mvn:org.apache.camel.quarkus:camel-quarkus-jms:@camel-quarkus.version@
springBoot.jms.dependencies=mvn:org.apache.camel.forage:forage-jms-starter:@project.version@,mvn:org.apache.camel.forage:forage-jms:@project.version@
plain.jdbc.dependencies=mvn:org.apache.camel.forage:forage-jdbc:@project.version@
quarkus.jdbc.dependencies=mvn:org.apache.camel.forage:forage-quarkus-jdbc:@project.version@,mvn:org.apache.camel.forage:forage-quarkus-jdbc-deployment:@project.version@,mvn:org.apache.camel.quarkus:camel-quarkus-sql:@camel-quarkus.version@
springBoot.jdbc.dependencies=mvn:org.apache.camel.forage:forage-jdbc-starter:@project.version@,mvn:org.apache.camel.forage:forage-jdbc:@project.version@

