jdbc.dependency.version=@project.version@
quarkus.version=@quarkus.version@
camel.version=@camel.version@
quarkus.artemis.jms.version=@quarkus.artemis.jms.version@

#-------------------------- dependencies --------------------------------------------
quarkus=mvn:org.apache.camel.forage:forage-quarkus-jms:@project.version@,mvn:org.apache.camel.forage:forage-quarkus-jms-deployment:@project.version@,mvn:org.apache.camel.quarkus:camel-quarkus-jms:@camel-quarkus.version@,mvn:org.apache.camel.forage:forage-quarkus-jms-deployment:@project.version@
artemis=mvn:io.quarkiverse.artemis:quarkus-artemis-jms:@quarkus.artemis.jms.version@
