<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.apache.camel.forage</groupId>
        <artifactId>integrationTests</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>integration-tests-jdbc</artifactId>
    <name>Camel Forage :: Integration Tests :: JDBC</name>

    <properties>
        <citrus.version>4.9.0-SNAPSHOT</citrus.version>
        <surefire-plugin.version>3.5.4</surefire-plugin.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.citrusframework</groupId>
            <artifactId>citrus-base</artifactId>
            <version>${citrus.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.citrusframework</groupId>
            <artifactId>citrus-testng</artifactId>
            <version>${citrus.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.citrusframework</groupId>
            <artifactId>citrus-camel</artifactId>
            <version>${citrus.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.citrusframework</groupId>
            <artifactId>citrus-spring</artifactId>
            <version>${citrus.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.citrusframework</groupId>
            <artifactId>citrus-validation-xml</artifactId>
            <version>${citrus.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.citrusframework</groupId>
            <artifactId>citrus-jbang-connector</artifactId>
            <version>${citrus.version}</version>
        </dependency>

        <dependency>
            <groupId>org.citrusframework</groupId>
            <artifactId>citrus-base</artifactId>
            <version>${citrus.version}</version>
        </dependency>
        <dependency>
            <groupId>org.citrusframework</groupId>
            <artifactId>citrus-groovy</artifactId>
            <version>${citrus.version}</version>
        </dependency>
        <dependency>
            <groupId>org.citrusframework</groupId>
            <artifactId>citrus-spring</artifactId>
            <version>${citrus.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.citrusframework</groupId>
            <artifactId>citrus-jbang-connector</artifactId>
            <version>${citrus.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-expression</artifactId>
            <version>6.2.11</version>
        </dependency>

        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-catalog</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-spring</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-spring-xml</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-yaml-dsl</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-endpointdsl</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
            <version>4.0.4</version>
        </dependency>

        <!-- Test scoped dependencies -->
        <dependency>
            <groupId>org.citrusframework</groupId>
            <artifactId>citrus-test-support</artifactId>
            <version>${citrus.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.citrusframework</groupId>
            <artifactId>citrus-testng</artifactId>
            <version>${citrus.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.citrusframework</groupId>
            <artifactId>citrus-yaml</artifactId>
            <version>${citrus.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.citrusframework</groupId>
            <artifactId>citrus-xml</artifactId>
            <version>${citrus.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.citrusframework</groupId>
            <artifactId>citrus-validation-xml</artifactId>
            <version>${citrus.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.citrusframework</groupId>
            <artifactId>citrus-validation-text</artifactId>
            <version>${citrus.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-base64</artifactId>
            <version>4.14.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-jsonpath</artifactId>
            <version>4.14.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j2-impl</artifactId>
            <version>2.25.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-timer</artifactId>
            <version>4.14.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-log</artifactId>
            <version>4.14.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.citrusframework.mvn</groupId>
                <artifactId>citrus-maven-plugin</artifactId>
                <version>${citrus.version}</version>
            </plugin>
        </plugins>
    </build>


</project>
